/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Negocio.Casino;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class FormBlackJack extends javax.swing.JFrame {

    /**
     * Creates new form FormBlackJack
     */
    Casino myCasino;
    JLabel[] manoJ1;
    JLabel[] manoJ2;
    public FormBlackJack(Casino myCasino) {
        initComponents();
        this.setLocationRelativeTo(this);
        txtApuesta1.setEnabled(false);
        txtApuesta2.setEnabled(false);
        txtNombre1.setEnabled(false);
        txtNombre2.setEnabled(false);
        this.myCasino=myCasino;
        
        SetImageLabel(lblCarta1, "src/images/AsDeCorazones.png");
        SetImageLabel(lblCarta2, "src/images/AsDeDiamantes.png");
        SetImageLabel(lblCarta3, "src/images/AsDePicas.png");
        SetImageLabel(lblCarta4, "src/images/AsDeTreboles.png");
        mostrarInfo(myCasino.enviarInfoPartido());
        /*SetImageLabel(lblCarta1, myCasino.getMyPartidos().getLast().getMyJugada1().getMyCartas().get(0).getImagen());
        SetImageLabel(lblCarta2, myCasino.getMyPartidos().getLast().getMyJugada1().getMyCartas().get(1).getImagen());
        SetImageLabel(lblCarta6, myCasino.getMyPartidos().getLast().getMyJugada2().getMyCartas().get(0).getImagen());
        SetImageLabel(lblCarta7, myCasino.getMyPartidos().getLast().getMyJugada2().getMyCartas().get(1).getImagen());
        */
        manoJ1 = new  JLabel[]{this.lblCarta1, this.lblCarta2, this.lblCarta3, this.lblCarta4, this.lblCarta5};
        manoJ2 = new  JLabel[]{this.lblCarta6, this.lblCarta7, this.lblCarta8, this.lblCarta9, this.lblCarta10};
        mostrarCartas(myCasino.mostrarCartas());
    }
    
    

        public void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
                labelName.setIcon(icon);
                this.repaint();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPartidoNo1 = new javax.swing.JLabel();
        lblBlackJack1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtApuesta2 = new javax.swing.JTextField();
        lblApuesta3 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        lblJugador1 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        txtApuesta1 = new javax.swing.JTextField();
        lblApuesta1 = new javax.swing.JLabel();
        lblCarta1 = new javax.swing.JLabel();
        lblCarta2 = new javax.swing.JLabel();
        lblCarta4 = new javax.swing.JLabel();
        lblCarta5 = new javax.swing.JLabel();
        lblCarta3 = new javax.swing.JLabel();
        btnOtraCarta2 = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnOtraCarta1 = new javax.swing.JButton();
        btnStop2 = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblCarta6 = new javax.swing.JLabel();
        lblCarta7 = new javax.swing.JLabel();
        lblCarta8 = new javax.swing.JLabel();
        lblCarta9 = new javax.swing.JLabel();
        lblCarta10 = new javax.swing.JLabel();
        btnAnotherGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblPartidoNo1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        lblPartidoNo1.setText("Partido No..*");

        lblBlackJack1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        lblBlackJack1.setText("BLACKJACK");

        lblJugador2.setText("Jugador 2");

        txtNombre1.setColumns(10);
        txtNombre1.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtApuesta2.setColumns(10);
        txtApuesta2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        lblApuesta3.setText("Apuesta:");

        lblNombre1.setText("Nombre: ");

        txtNombre2.setColumns(10);
        txtNombre2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        lblJugador1.setText("Jugador 1");

        lblNombre4.setText("Nombre: ");

        txtApuesta1.setColumns(10);
        txtApuesta1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApuesta1ActionPerformed(evt);
            }
        });

        lblApuesta1.setText("Apuesta:");

        lblCarta1.setText("1");
        lblCarta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCarta2.setText("2");
        lblCarta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCarta4.setText("4");
        lblCarta4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCarta5.setText("5");
        lblCarta5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCarta3.setText("3");
        lblCarta3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnOtraCarta2.setText("Otra Carta");
        btnOtraCarta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtraCarta2ActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");

        btnOtraCarta1.setText("Otra Carta");
        btnOtraCarta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtraCarta1ActionPerformed(evt);
            }
        });

        btnStop2.setText("Stop");
        btnStop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStop2ActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lblCarta6.setText("1");
        lblCarta6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCarta7.setText("2");
        lblCarta7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCarta8.setText("3");
        lblCarta8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCarta9.setText("4");
        lblCarta9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCarta10.setText("5");
        lblCarta10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAnotherGame.setText("Jugar otro Juego");
        btnAnotherGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnotherGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPartidoNo1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblApuesta1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtApuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNombre1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblJugador1)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnAnotherGame)
                                .addGap(302, 302, 302)
                                .addComponent(btnNuevo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnOtraCarta1)
                                        .addGap(58, 58, 58)
                                        .addComponent(btnStop2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                                .addComponent(lblCarta6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblApuesta3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtApuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblNombre4)
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblJugador2)
                                                .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCarta7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCarta8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCarta9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCarta10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnOtraCarta2)
                                .addGap(78, 78, 78)
                                .addComponent(btnStop)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBlackJack1)
                        .addGap(413, 413, 413))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPartidoNo1)
                .addGap(18, 18, 18)
                .addComponent(lblBlackJack1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJugador1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre1)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApuesta1)
                            .addComponent(txtApuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJugador2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre4)
                            .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApuesta3))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarta9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarta8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarta10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarta7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarta6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOtraCarta1)
                        .addComponent(btnStop2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOtraCarta2)
                        .addComponent(btnStop)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnotherGame)
                    .addComponent(btnNuevo))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApuesta1ActionPerformed

    private void btnAnotherGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnotherGameActionPerformed
        
        //formElJu.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnAnotherGameActionPerformed

    private void btnOtraCarta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtraCarta1ActionPerformed
        String salida=myCasino.pedirCartaBlackjack("1");
        if(salida.equalsIgnoreCase("Ya tienes una mano de 5 cartas")){
            Ventana.imp(salida, "Sistema");
        }
    }//GEN-LAST:event_btnOtraCarta1ActionPerformed

    private void btnOtraCarta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtraCarta2ActionPerformed
        String salida=myCasino.pedirCartaBlackjack("2");
        if(salida.equalsIgnoreCase("Ya tienes una mano de 5 cartas")){
            Ventana.imp(salida, "Sistema");
        }
    }//GEN-LAST:event_btnOtraCarta2ActionPerformed

    private void btnStop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStop2ActionPerformed
        if(myCasino.plantarJugador1()){
            myCasino.mostrarCartas();
            
        }
        
    }//GEN-LAST:event_btnStop2ActionPerformed

    void mostrarInfo(String info){
        String[] infor=new String[6];
        infor=info.split("/");
        this.txtNombre1.setText(infor[0]);
        this.txtNombre2.setText(infor[1]);
        this.txtApuesta1.setText(infor[2]);
        this.txtApuesta2.setText(infor[3]);
        this.lblPartidoNo1.setText("Partido No. 01"+infor[4]);
        this.lblJugador2.setText((infor[5].equalsIgnoreCase("0")) ? "Crupier":"Jugador 2");
    }
    
    void mostrarCartas(String info){
        String[] infor=new String[10];
        infor=info.split("/");
        int i=0;
        for(JLabel e:manoJ1){
            if(!infor[i].equalsIgnoreCase("")){
                SetImageLabel(manoJ1[i], infor[i]);
            }
            i++;
        }
        for(JLabel e:manoJ2){
            if(!infor[i].equalsIgnoreCase("")){
                SetImageLabel(manoJ2[i-5], infor[i]);
            }
            i++;
        }
    }
    /**
     * @param args the command line arguments
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnotherGame;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOtraCarta1;
    private javax.swing.JButton btnOtraCarta2;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton btnStop2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblApuesta1;
    private javax.swing.JLabel lblApuesta3;
    private javax.swing.JLabel lblBlackJack1;
    private javax.swing.JLabel lblCarta1;
    private javax.swing.JLabel lblCarta10;
    private javax.swing.JLabel lblCarta2;
    private javax.swing.JLabel lblCarta3;
    private javax.swing.JLabel lblCarta4;
    private javax.swing.JLabel lblCarta5;
    private javax.swing.JLabel lblCarta6;
    private javax.swing.JLabel lblCarta7;
    private javax.swing.JLabel lblCarta8;
    private javax.swing.JLabel lblCarta9;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblPartidoNo1;
    private javax.swing.JTextField txtApuesta1;
    private javax.swing.JTextField txtApuesta2;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    // End of variables declaration//GEN-END:variables
}
