package Vista;

import Negocio.Casino;
/**
 *
 * @author Usuario
 */
public class FormRegistrarJugador extends javax.swing.JFrame {
    private Casino myCasino;
    /**
     * Creates new form FormRegistrar
     */
    public FormRegistrarJugador(Casino myCasino) {
        initComponents();
        this.myCasino=myCasino;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistrarJugador = new javax.swing.JLabel();
        lblNombreRegistrar = new javax.swing.JLabel();
        lblCedulaRegistrar = new javax.swing.JLabel();
        lblMontoRegistrar = new javax.swing.JLabel();
        txtNombreRegistrar = new javax.swing.JTextField();
        txtCedulaRegistrar = new javax.swing.JTextField();
        txtMontoRegistrar = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lblEdadRegistrar = new javax.swing.JLabel();
        txtEdadRegistrar = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        txtTelefonoRegistrar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRegistrarJugador.setText("Registrar Jugador");

        lblNombreRegistrar.setText("Nombre: ");

        lblCedulaRegistrar.setText("Cedula: ");

        lblMontoRegistrar.setText("Monto Inicial:");

        txtNombreRegistrar.setColumns(10);
        txtNombreRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRegistrarActionPerformed(evt);
            }
        });

        txtCedulaRegistrar.setColumns(10);

        txtMontoRegistrar.setColumns(10);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblEdadRegistrar.setText("Edad:");

        txtEdadRegistrar.setColumns(10);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel2.setText("Telefono:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)
                        .addGap(77, 77, 77)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(lblRegistrarJugador))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreRegistrar)
                                    .addComponent(lblCedulaRegistrar)
                                    .addComponent(lblMontoRegistrar)
                                    .addComponent(lblEdadRegistrar)
                                    .addComponent(jLabel2))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdadRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCedulaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMontoRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblRegistrarJugador)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRegistrar)
                    .addComponent(txtNombreRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaRegistrar)
                    .addComponent(txtCedulaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoRegistrar)
                    .addComponent(txtMontoRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadRegistrar)
                    .addComponent(txtEdadRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRegistrarActionPerformed
        
    }//GEN-LAST:event_txtNombreRegistrarActionPerformed
    
    public void limpiar(){
        txtNombreRegistrar.setText("");        
        txtCedulaRegistrar.setText("");     
        txtMontoRegistrar.setText(""); 
        txtEdadRegistrar.setText("");
        txtTelefonoRegistrar.setText("");
       
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombre = txtNombreRegistrar.getText();
        String cedula = txtCedulaRegistrar.getText();
        int montoIni=0;
        int edad=0;
        String telefono=txtTelefonoRegistrar.getText();
        
        if(nombre.isEmpty() || cedula.isEmpty() || txtMontoRegistrar.getText().isEmpty() || txtEdadRegistrar.getText().isEmpty()||telefono.isEmpty()){ 
            Ventana.imp("LLENE todos los campos", "mensaje");
            return;
        }
        
        try{
            montoIni=Integer.parseInt(txtMontoRegistrar.getText());
        }catch(NumberFormatException e){
            Ventana.imp("El monto debe ser un numero.", "Sistema");
            txtMontoRegistrar.setText("");
            return;
        }
        
        try{
            edad=Integer.parseInt(txtEdadRegistrar.getText());
        }catch(NumberFormatException e){
            Ventana.imp("La edad debe ser un numero.", "Sistema");
            txtEdadRegistrar.setText("");
            return;
        }
        
        String salida = myCasino.registrarJugador(nombre, cedula, edad, montoIni, telefono);
        
        Ventana.imp(salida,"Sistema");
        
        if(salida.equalsIgnoreCase("Registro exitoso")){
            this.limpiar();
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FormPrePartido jugar = new FormPrePartido(myCasino);
        jugar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCedulaRegistrar;
    private javax.swing.JLabel lblEdadRegistrar;
    private javax.swing.JLabel lblMontoRegistrar;
    private javax.swing.JLabel lblNombreRegistrar;
    private javax.swing.JLabel lblRegistrarJugador;
    private javax.swing.JTextField txtCedulaRegistrar;
    private javax.swing.JTextField txtEdadRegistrar;
    private javax.swing.JTextField txtMontoRegistrar;
    private javax.swing.JTextField txtNombreRegistrar;
    private javax.swing.JTextField txtTelefonoRegistrar;
    // End of variables declaration//GEN-END:variables
}
